### ISSUE TITLE
How to predict crystal systems for a custom (user defined) dataset

### ISSUE THREAD

**Issue by Qais-Ali-5** [JunwenBai/crystal-classification#1]
Thanks for the nice work! The Readme file shows that dataset is being taken from **data/crystal_structures.npz**. I would like to ask that if I have a certain dataset of XRD (be it synthetic or measured) to predict the crystal systems or space groups for this dataset, could you please explain the steps to do that?

**Comment by JunwenBai** [comment]
Hi, Qais,

Thx for your interest in our work!
`crystal_structures.npz` is very simple and straightforward. You can customize your own dataset just the same as it.

In detail, `crystal_structures.npz` has 2 fields, `xrd` and `crystal_system`.

- `xrd` is an array of shape [5479, 2000], which means the dataset has 5479 samples, and each of the sample is a 2000-d vector. This 2000-d vector is considered the "feature"
- `crystal_system` is the labels, of shape [5479]. Each label indicates one of the (7 crystal systems)[https://en.wikipedia.org/wiki/Crystal_system].

The model reads the 2000-d feature for each sample, and predicts the crystal system (0-6). You can formalize your dataset to be `n`-d feature and predict the desired label/class too.

**Comment by Qais-Ali-5** [comment]
Hi Junwen,
Thank you for your kind response. I have following follow-up queries. 
1- Regarding `xrd`, what is the physical meaning of the feature? Is it the intensity of the peaks? Because for my case for example I have 250 experimentally measured 1D XRD patterns and each pattern has two columns, i.e. `2theta` and `intensity` of shape [5400, 5400]. So, if I follow the way to formulate `xrd` as you suggested then I will have a shape of [250,5400], but I am not sure whether it should be intensity or 2theta column, which you consider in `xrd` as a "feature"? 
2- And then the `crystal_system` shape would be [250], but how to fill this array for 7 crystal systems for each "feature"? Because this is exactly what I would like to predict for the experimental xrd patterns and I am not aware which crystal systems exit in the pattern, although I have a rough idea. Secondly, if the xrd pattern contains more than one crystal systems, will the code predict that too or it can only predict one crystal system XRD per pattern?

**Comment by JunwenBai** [comment]
1. In my case, `xrd` feature is the x-ray diffraction pattern which is essentially a 2000-d vector. See the left figure from the [overview](https://github.com/JunwenBai/X-Ray-crystal-classification?tab=readme-ov-file#overview) as an example. In your case, you can keep [5400, 5400], s.t., you'll have [250, 5400, 5400]. You could extend the neural network to be able to read [2500, 2500] feature for each of 250 samples.
2. If you want to use my model directly, you'll have to extract a similar 2000-d vector, like the left figure from the [overview](https://github.com/JunwenBai/X-Ray-crystal-classification?tab=readme-ov-file#overview) as an example. Some other details regarding the 2000-d vector can be found in the [paper](https://www.cs.cornell.edu/gomes/pdf/2019_bai_icassp_imitation_refinement.pdf). If you want to use your raw [5400, 5400], you'll have to re-train your own new model. Regarding whether my model can predict more than one crystal systems, the answer is No. My model can only predict 1 crystal system.

**Comment by Qais-Ali-5** [comment]
Thank you very much for your kind explanation!
